sudo: required
language: c
os:
  - linux
services:
  - docker
env:
  - DOCKER_IMAGE=centos:6
  - DOCKER_IMAGE=centos:7
  - DOCKER_IMAGE=debian:stable
  # https://bugs.launchpad.net/ubuntu/+source/slurm-llnl/+bug/1802374
  #- DOCKER_IMAGE=ubuntu:latest

before_script:
  # these steps prep the source as if it were a distribution tarball
  - sudo apt-get install -y gperf ragel bison
  - sh autogen.sh
  - (cd drmaa_utils && ./configure)
  - make -C drmaa_utils/drmaa_utils conf_tab.c conf_tab.h datetime_tab.c datetime_tab.h drmaa_attrib.c timedelta.c
  - make -C drmaa_utils distclean
  # set up build env
  - |
    case "$DOCKER_IMAGE" in
        centos:6)
            docker run --cidfile .cid $DOCKER_IMAGE /bin/sh -c 'curl -o /etc/yum.repos.d/galaxy.repo https://depot.galaxyproject.org/yum/galaxy.repo && yum install -y "@development tools" slurm slurm-devel'
            ;;
        centos:*)
            docker run --cidfile .cid $DOCKER_IMAGE /bin/sh -c 'yum-config-manager --add-repo https://depot.galaxyproject.org/yum/galaxy.repo && yum install -y "@development tools" slurm slurm-devel'
            ;;
        debian:*|ubuntu:*)
            docker run --cidfile .cid --env DEBIAN_FRONTEND=noninteractive $DOCKER_IMAGE /bin/sh -c 'apt-get -qq update && apt-get install -y build-essential slurm-wlm libslurm-dev libslurmdb-dev'
            ;;
        *)
            echo "unsupported image: $DOCKER_IMAGE"
            return 1
            ;;
    esac
  - docker commit $(cat .cid) ci/$DOCKER_IMAGE

script:
  - docker run --volume $(pwd):$(pwd) --workdir $(pwd) --user $(id -u):$(id -g) ci/$DOCKER_IMAGE ./configure
  - docker run --volume $(pwd):$(pwd) --workdir $(pwd) --user $(id -u):$(id -g) ci/$DOCKER_IMAGE make
